// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class ApiLogsAttendance
{
    public long Id { get; set; }

    public DateTime? TimeStamp { get; set; }

    public string Method { get; set; }

    public string Path { get; set; }

    public string Query { get; set; }

    public string Json { get; set; }

    public string Ip { get; set; }

    public DateTime? CreatedDate { get; set; }
}