// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class ApiToken
{
    public long Id { get; set; }

    public string ApiName { get; set; }

    public string SalesId { get; set; }

    public string Token { get; set; }

    public string RefreshToken { get; set; }

    public DateTime? LastUsedAt { get; set; }

    public DateTime? ExpiredToken { get; set; }

    public ulong? Active { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}