// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class ApprovalType
{
    public long Id { get; set; }

    public string ApprovalId { get; set; }

    public string ApprovalType1 { get; set; }

    public string ApprovalName { get; set; }

    public string Description { get; set; }

    public ulong? Active { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}