// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class AttendanceLog
{
    public long Id { get; set; }

    public string LogId { get; set; }

    public string SalesId { get; set; }

    public string AbsentCode { get; set; }

    public string AbsentType { get; set; }

    public DateTime? AttendanceDate { get; set; }

    public string Longitude { get; set; }

    public string Latitude { get; set; }

    public int? Month { get; set; }

    public int? Year { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}