// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class LabelSecondaryDisplay
{
    public long Id { get; set; }

    public string LabelName { get; set; }

    public string PathFile { get; set; }

    public string HashFile { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }
}