// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class LoginDevice
{
    public long Id { get; set; }

    public string SalesId { get; set; }

    public string DeviceId { get; set; }

    public DateTime? LoginDate { get; set; }

    public DateTime? LogoutDate { get; set; }

    public ulong? IsLogin { get; set; }
}