// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class LoginLog
{
    public long Id { get; set; }

    public string Username { get; set; }

    public string SalesId { get; set; }

    public string SalesName { get; set; }

    public DateTime? LoginDate { get; set; }

    public string LoginTerminal { get; set; }

    public DateTime? LogoutDate { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}