// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class Mechanisme
{
    public long Id { get; set; }

    public string Name { get; set; }

    public ulong? Active { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }
}