// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class MenuRole
{
    public long Id { get; set; }

    public string RoleId { get; set; }

    public string MenuIdHeader { get; set; }

    public string MenuIdChild { get; set; }

    public int? Sort { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}