// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class MenuChild
{
    public long Id { get; set; }

    public string MenuChildId { get; set; }

    public string MenuChildName { get; set; }

    public string ControllerName { get; set; }

    public string ActionName { get; set; }

    public string Description { get; set; }

    public ulong? Active { get; set; }

    public int? Sort { get; set; }

    public DateTime? CreateDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}