// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class OrderProduct
{
    public long Id { get; set; }

    public string OrderId { get; set; }

    public string InvoiceId { get; set; }

    public DateTime? OrderDate { get; set; }

    public string SalesId { get; set; }

    public string StoreId { get; set; }

    public string ProductId { get; set; }

    public int? Qty { get; set; }

    public int? Price { get; set; }

    public decimal? Subtotal { get; set; }

    public string FilePhoto { get; set; }

    public string UrlPhoto { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}