// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class OrderDetail
{
    public long Id { get; set; }

    public string OrderDetailId { get; set; }

    public string OrderId { get; set; }

    public string ProductId { get; set; }

    public string ProductName { get; set; }

    public int Quantity { get; set; }

    public string Uom { get; set; }

    public decimal UnitPrice { get; set; }

    public decimal? DiscountPercent { get; set; }

    public decimal? DiscountAmount { get; set; }

    public decimal Subtotal { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}