// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class PasswordResetToken
{
    public string Email { get; set; }

    public string Token { get; set; }

    public DateTime? CreatedAt { get; set; }
}