// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class PhotoProductPriceCompetitor
{
    public long Id { get; set; }

    public string CompetitorId { get; set; }

    public string LocationName { get; set; }

    public string SalesId { get; set; }

    public string StoreId { get; set; }

    public string ProductId { get; set; }

    public string RegionId { get; set; }

    public string AreaId { get; set; }

    public string CityId { get; set; }

    public decimal? PriceCompetitor { get; set; }

    public string FilePhoto { get; set; }

    public string UrlPhoto { get; set; }

    public int? Month { get; set; }

    public int? Year { get; set; }

    public string Note { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}