// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class ProductStock
{
    public long Id { get; set; }

    public string ProductStockId { get; set; }

    public string SalesId { get; set; }

    public string ProductId { get; set; }

    public string StoreId { get; set; }

    public string RegionId { get; set; }

    public string AreaId { get; set; }

    public string CityId { get; set; }

    public long? Stock { get; set; }

    public DateOnly? StockDate { get; set; }

    public string FilePhoto { get; set; }

    public string FileUrlPhoto { get; set; }

    public int? Month { get; set; }

    public int? Year { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}