// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class RentalDisplay
{
    public long Id { get; set; }

    public string RentalDisplayId { get; set; }

    public string SalesId { get; set; }

    public string DisplayId { get; set; }

    public DateOnly? RentalDateFrom { get; set; }

    public DateOnly? RentalDateTo { get; set; }

    public string FilePhoto { get; set; }

    public string FileUrlPhoto { get; set; }

    public int? Month { get; set; }

    public int? Year { get; set; }

    public string Description { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}