// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class StoreVisit
{
    public long Id { get; set; }

    public string StoreVisitId { get; set; }

    public string SalesId { get; set; }

    public string StoreId { get; set; }

    public string FilePhotoVisit { get; set; }

    public string UrlPhotoVisit { get; set; }

    public string FilePhotoVisitOut { get; set; }

    public string UrlPhotoVisitOut { get; set; }

    public int Month { get; set; }

    public int Year { get; set; }

    public DateOnly VisitDate { get; set; }

    public DateOnly? VisitDateOut { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }
}