// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class SubmissionLeave
{
    public long Id { get; set; }

    public string LeaveId { get; set; }

    public string SalesId { get; set; }

    public DateOnly LeaveDateFrom { get; set; }

    public DateOnly LeaveDateTo { get; set; }

    public int TotalLeave { get; set; }

    public string AbsentCode { get; set; }

    public DateTime? ApproveDate { get; set; }

    public string ApproveBy { get; set; }

    public DateTime? RejectDate { get; set; }

    public string RejectBy { get; set; }

    public string ReasonReject { get; set; }

    public DateTime? CancelDate { get; set; }

    public string CancelBy { get; set; }

    public string Description { get; set; }

    public string FilePhoto { get; set; }

    public string FileUrlPhoto { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}