// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class TicketingDevice
{
    public long Id { get; set; }

    public string SalesId { get; set; }

    public string SalesName { get; set; }

    public string DeviceId { get; set; }

    public string Email { get; set; }

    public string Telephone { get; set; }

    public ulong? Status { get; set; }

    public DateTime? ApproveDate { get; set; }

    public string ApproveBy { get; set; }

    public DateTime? RejectDate { get; set; }

    public string RejectBy { get; set; }

    public string ReasonReject { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public string UpdatedBy { get; set; }
}