// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class User
{
    public ulong Id { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public DateTime? EmailVerifiedAt { get; set; }

    public string Password { get; set; }

    public string RememberToken { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}