// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class VArea
{
    public long Id { get; set; }

    public string AreaId { get; set; }

    public string AreaName { get; set; }

    public string RegionId { get; set; }

    public string RegionName { get; set; }

    public ulong? Active { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}