// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class VAttendanceOvertime
{
    public long Id { get; set; }

    public string SalesId { get; set; }

    public string SalesName { get; set; }

    public string OvertimeId { get; set; }

    public DateTime? IncomingAttendance { get; set; }

    public DateTime? RepeatAttendance { get; set; }

    public string FilePhoto { get; set; }

    public string FileUrlPhoto { get; set; }

    public int? Month { get; set; }

    public int? Year { get; set; }

    public string Description { get; set; }

    public ulong? Active { get; set; }

    public DateTime? ApproveDate { get; set; }

    public string ApproveBy { get; set; }

    public DateTime? RejectDate { get; set; }

    public string RejectBy { get; set; }

    public string RejectReason { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}