// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class VAttendance
{
    public long Id { get; set; }

    public string AttendanceId { get; set; }

    public string SalesId { get; set; }

    public string SalesName { get; set; }

    public string AbsentCode { get; set; }

    public string AbsentName { get; set; }

    public DateTime? IncomingAttendance { get; set; }

    public string IncomingLongitude { get; set; }

    public string IncomingLatitude { get; set; }

    public string IncomingFilePhoto { get; set; }

    public string IncomingUrlPhoto { get; set; }

    public DateTime? RepeatAttendance { get; set; }

    public string RepeatLongitude { get; set; }

    public string RepeatLatitude { get; set; }

    public string RepeatFilePhoto { get; set; }

    public string RepeatUrlPhoto { get; set; }

    public int? Month { get; set; }

    public int? Year { get; set; }

    public string Description { get; set; }

    public ulong? Active { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}