// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class VDashboardAttendance
{
    public ulong Id { get; set; }

    public string SalesId { get; set; }

    public string SalesName { get; set; }

    public string CreatedDate { get; set; }

    public DateTime? IncomingAttendance { get; set; }

    public DateTime? RepeatAttendance { get; set; }
}