// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class VDashboardStoreVisitMonthly
{
    public ulong Id { get; set; }

    public string SalesId { get; set; }

    public string SalesName { get; set; }

    public int? Month { get; set; }

    public int? Year { get; set; }

    public long? TotalVisit { get; set; }

    public long? TargetVisit { get; set; }

    public decimal? Percentase { get; set; }
}