// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class VDashboardTotalAttendance
{
    public string SalesName { get; set; }

    public long TotalAttendance { get; set; }

    public int? Month { get; set; }

    public int? Year { get; set; }
}