// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class VLogStock
{
    public long Id { get; set; }

    public string ProductId { get; set; }

    public string ProductName { get; set; }

    public string StoreId { get; set; }

    public string StoreName { get; set; }

    public DateTime? StockDate { get; set; }

    public int? StockBefore { get; set; }

    public int? StockAfter { get; set; }

    public int? Month { get; set; }

    public int? Year { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}