// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class VLogin
{
    public long Id { get; set; }

    public string SalesId { get; set; }

    public string SalesName { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string RoleId { get; set; }

    public string RoleName { get; set; }

    public string PositionId { get; set; }

    public string PositionName { get; set; }

    public string Email { get; set; }

    public ulong? Active { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }
}