// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class VMenuRole
{
    public long Id { get; set; }

    public string RoleId { get; set; }

    public string RoleName { get; set; }

    public string MenuHeaderId { get; set; }

    public string MenuHeaderName { get; set; }

    public ulong? ActiveHeader { get; set; }

    public int? SortHeader { get; set; }

    public string MenuChildId { get; set; }

    public string MenuChildName { get; set; }

    public string ControllerName { get; set; }

    public string ActionName { get; set; }

    public ulong? ActiveChild { get; set; }

    public int? SortChild { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}