// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class VPhotoPromotion
{
    public long Id { get; set; }

    public string PromotionTrId { get; set; }

    public string SalesId { get; set; }

    public string SalesName { get; set; }

    public string StoreId { get; set; }

    public string StoreName { get; set; }

    public string PromotionId { get; set; }

    public string PromotionName { get; set; }

    public decimal? WeeklyPromotionFees { get; set; }

    public decimal? BudgetPromotionStore { get; set; }

    public string FilePhoto { get; set; }

    public string UrlPhoto { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public ulong? Active { get; set; }

    public string Description { get; set; }

    public int? Month { get; set; }

    public int? Year { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}