// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class VPosition
{
    public long Id { get; set; }

    public string DepartmentId { get; set; }

    public string DepartmentName { get; set; }

    public string DivisionId { get; set; }

    public string DivisionName { get; set; }

    public string PositionId { get; set; }

    public string PositionName { get; set; }

    public ulong? Active { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}