// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class VProductPricing
{
    public long Id { get; set; }

    public string ProductPricingId { get; set; }

    public string SalesId { get; set; }

    public string SalesName { get; set; }

    public string ProductId { get; set; }

    public string ProductName { get; set; }

    public string CategoryId { get; set; }

    public string CategoryName { get; set; }

    public string VariantId { get; set; }

    public string VariantName { get; set; }

    public string StoreId { get; set; }

    public string StoreName { get; set; }

    public decimal? NormalPrice { get; set; }

    public decimal? PromoPrice { get; set; }

    public decimal? CompetitorPrice { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public string Posm { get; set; }

    public string Mechanisme { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}