// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class VRegionStore
{
    public long Id { get; set; }

    public string RegionId { get; set; }

    public string RegionName { get; set; }

    public string AreaId { get; set; }

    public string AreaName { get; set; }

    public string CityId { get; set; }

    public string CityName { get; set; }

    public string SalesId { get; set; }

    public string SalesName { get; set; }

    public string StoreId { get; set; }

    public string StoreName { get; set; }

    public string Longitude { get; set; }

    public string Latitude { get; set; }

    public int Radius { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }
}