// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class VRoleMenuHeader
{
    public string RoleId { get; set; }

    public string RoleName { get; set; }

    public string MenuHeaderId { get; set; }

    public string MenuHeaderName { get; set; }

    public ulong? ActiveHeader { get; set; }

    public int? SortHeader { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}