// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class VSale
{
    public long Id { get; set; }

    public string SalesId { get; set; }

    public string SalesName { get; set; }

    public string DepartmentId { get; set; }

    public string DepartmentName { get; set; }

    public string DivisionId { get; set; }

    public string DivisionName { get; set; }

    public string PositionId { get; set; }

    public string PositionName { get; set; }

    public string RoleId { get; set; }

    public string RoleName { get; set; }

    public string Gender { get; set; }

    public string Status { get; set; }

    public string Religion { get; set; }

    public string Education { get; set; }

    public string Address { get; set; }

    public string PlaceOfBirth { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string Email { get; set; }

    public string Telephone { get; set; }

    public string UserName { get; set; }

    public ulong? IsLogin { get; set; }

    public ulong? IsLogout { get; set; }

    public string LoginTerminal { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}