// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class VSalesTracking
{
    public string SalesId { get; set; }

    public string SalesName { get; set; }

    public string Gender { get; set; }

    public string Status { get; set; }

    public string Religion { get; set; }

    public string Education { get; set; }

    public string Address { get; set; }

    public string Email { get; set; }

    public string Telephone { get; set; }

    public string LoginTerminal { get; set; }

    public string SalesLocationId { get; set; }

    public string Activity { get; set; }

    public double? Latitude { get; set; }

    public double? Longitude { get; set; }

    public int? Month { get; set; }

    public int? Year { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}