// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class VSalesStructure
{
    public long Id { get; set; }

    public string SalesIdParent { get; set; }

    public string SalesNameParent { get; set; }

    public string SalesIdChild { get; set; }

    public string SalesNameChild { get; set; }

    public string RegionId { get; set; }

    public string RegionName { get; set; }

    public string AreaId { get; set; }

    public string AreaName { get; set; }

    public string CityId { get; set; }

    public string CityName { get; set; }

    public string Description { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}