// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class VSurveyResponse
{
    public string SurveyResponseId { get; set; }

    public string SurveyId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string StoreId { get; set; }

    public string StoreName { get; set; }

    public string SurveyQuestionId { get; set; }

    public string QuestionText { get; set; }

    public string QuestionType { get; set; }

    public string Options { get; set; }

    public string RespondentName { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}