// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEB_FMCG.Models;

public partial class VUserRoleAccess
{
    public long Id { get; set; }

    public string SalesId { get; set; }

    public string SalesName { get; set; }

    public string UserName { get; set; }

    public string RoleId { get; set; }

    public string RoleName { get; set; }

    public ulong? IsCreate { get; set; }

    public ulong? IsUpdate { get; set; }

    public ulong? IsDelete { get; set; }

    public ulong? Active { get; set; }

    public string Description { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }
}